export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAIL = "PRODUCTS_DETAILS_FAIL";

export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL";


export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAIL = "CURRENT_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";


export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";


export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const CART_PRODUCTS_REQUEST = "CART_PRODUCTS_REQUEST";
export const CART_PRODUCTS_SUCCESS = "CART_PRODUCTS_SUCCESS";
export const CART_PRODUCTS_FAIL = "CART_PRODUCTS_FAIL";

export const DELETE_ALL_CART_PRODUCTS_REQUEST = "DELETE_ALL_CART_PRODUCTS_REQUEST";
export const DELETE_ALL_CART_PRODUCTS_SUCCESS = "DELETE_ALL_CART_PRODUCTS_SUCCESS";
export const DELETE_ALL_CART_PRODUCTS_FAIL = "DELETE_ALL_CART_PRODUCTS_FAIL";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAIL = "ADMIN_ALL_ORDERS_FAIL";

export const ADMIN_UPDATE_ORDERS_REQUEST = "ADMIN_UPDATE_ORDERS_REQUEST";
export const ADMIN_UPDATE_ORDERS_SUCCESS = "ADMIN_UPDATE_ORDERS_SUCCESS";
export const ADMIN_UPDATE_ORDERS_FAIL = "ADMIN_UPDATE_ORDERS_FAIL";

export const ADMIN_DELETE_ORDERS_REQUEST = "ADMIN_DELETE_ORDERS_REQUEST";
export const ADMIN_DELETE_ORDERS_SUCCESS = "ADMIN_DELETE_ORDERS_SUCCESS";
export const ADMIN_DELETE_ORDERS_FAIL = "ADMIN_DELETE_ORDERS_FAIL";

export const ADMIN_GET_ALL_USERS_REQUEST = "ADMIN_GET_ALL_USERS_REQUEST";
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GET_ALL_USERS_SUCCESS";
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GET_ALL_USERS_FAIL";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";

export const ADMIN_GET_USER_REQUEST = "ADMIN_GET_USER_REQUEST";
export const ADMIN_GET_USER_SUCCESS = "ADMIN_GET_USER_SUCCESS";
export const ADMIN_GET_USER_FAIL = "ADMIN_GET_USER_FAIL";


export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL";

export const ADMIN_UPDATE_ISBLOCKED_USER_REQUEST = "ADMIN_UPDATE_ISBLOCKED_USER_REQUEST";
export const ADMIN_UPDATE_ISBLOCKED_USER_SUCCESS = "ADMIN_UPDATE_ISBLOCKED_USER_SUCCESS";
export const ADMIN_UPDATE_ISBLOCKED_USER_FAIL = "ADMIN_UPDATE_ISBLOCKED_USER_FAIL";

export const ADMIN_GET_ALL_REVIEWS_REQUEST = "ADMIN_GET_ALL_REVIEWS_REQUEST";
export const ADMIN_GET_ALL_REVIEWS_SUCCESS = "ADMIN_GET_ALL_REVIEWS_SUCCESS";
export const ADMIN_GET_ALL_REVIEWS_FAIL = "ADMIN_GET_ALL_REVIEWS_FAIL";


export const ADMIN_DELETE_REVIEWS_REQUEST = "ADMIN_DELETE_REVIEWS_REQUEST";
export const ADMIN_DELETE_REVIEWS_SUCCESS = "ADMIN_DELETE_REVIEWS_SUCCESS";
export const ADMIN_DELETE_REVIEWS_FAIL = "ADMIN_DELETE_REVIEWS_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const USER_REVIEW_REQUEST = "USER_REVIEW_REQUEST";
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS";
export const USER_REVIEW_FAIL = "USER_REVIEW_FAIL";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";


export const USER_ADDRESS_REQUEST = "USER_ADDRESS_REQUEST";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
export const USER_ADDRESS_FAIL = "USER_ADDRESS_FAIL";

export const CURRENT_LOCATION = "CURRENT_LOCATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

